# Generated by Django 4.2 on 2023-05-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_products', '0004_alter_cartproduct_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ['product__seller']},
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
