# Generated by Django 4.2 on 2023-05-05 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
    ]
