# Generated by Django 4.2 on 2023-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('wishlists', '0004_alter_wishlist_unique_together_wishlist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlists', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='created_at',
        ),
    ]
