# Generated by Django 4.2 on 2023-05-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproducts',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
