# Generated by Django 4.2 on 2023-05-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderedproducts_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproducts',
            name='user',
        ),
    ]
